# Generated by Django 4.2 on 2025-01-08 11:53

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_token',
            field=models.CharField(default=users.models.generate_verification_token, max_length=50),
        ),
    ]
