# Generated by Django 5.0.6 on 2025-10-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
