# Generated by Django 5.0.6 on 2025-11-05 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_timezone_user_last_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_timezone',
            new_name='timezone',
        ),
    ]
