# Generated by Django 5.0.6 on 2026-01-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_email',
            field=models.EmailField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
