# Generated by Django 5.0.6 on 2025-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actionable_steps',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='task',
            name='task_timeline',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
