# Generated by Django 5.0.6 on 2025-02-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_aigoal_aitask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
