# Generated by Django 5.0.6 on 2025-02-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_alter_aitask_due_date_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
