# Generated by Django 5.0.6 on 2025-02-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_aitask_reminder_time_task_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
