# Generated by Django 5.0.6 on 2025-02-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigoal',
            name='category',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('priority', 'Priority')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='aigoal',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('priority', 'Priority')], default='monthly', max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
