# Generated by Django 5.0.6 on 2025-02-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_task_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_updated',
        ),
    ]
