# Generated by Django 5.0.6 on 2025-02-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0009_aigoal_category_aigoal_progress_goal_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigoal',
            name='category',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('priority', 'Priority')], max_length=10, null=True),
        ),
    ]
