# Generated by Django 5.0.6 on 2025-02-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_aitask_last_updated_task_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigoal',
            name='category',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.CharField(blank=True, choices=[('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
    ]
