# Generated by Django 5.0.6 on 2025-02-24 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0013_alter_aigoal_category_alter_goal_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
