# Generated by Django 5.0.6 on 2025-02-24 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_aitask_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitask',
            name='order',
        ),
    ]
