# Generated by Django 5.0.6 on 2025-03-01 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_remove_task_last_updated'),
        ('goals', '0015_remove_aitask_order'),
    ]

    operations = [
    ]
