# Generated by Django 5.0.6 on 2025-03-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0016_merge_20250301_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
