# Generated by Django 5.0.6 on 2025-03-24 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0017_task_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitask',
            name='actionable_steps',
        ),
        migrations.RemoveField(
            model_name='task',
            name='actionable_steps',
        ),
        migrations.AddField(
            model_name='aitask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='goals.aitask'),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='goals.task'),
        ),
    ]
