# Generated by Django 5.0.6 on 2025-03-24 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0018_remove_aitask_actionable_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
