# Generated by Django 5.0.6 on 2025-03-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0019_aitask_description_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitask',
            name='parent_task',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.JSONField(default=list),
        ),
    ]
