# Generated by Django 5.0.6 on 2025-03-24 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0020_alter_aitask_parent_task_alter_task_parent_task'),
    ]

    operations = [
    ]
