# Generated by Django 5.0.6 on 2025-03-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0021_auto_20250324_2355'),
    ]

    operations = [
    ]
