# Generated by Django 5.0.6 on 2025-03-25 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0022_auto_20250325_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aitask',
            name='parent_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent_task',
        ),
    ]
