# Generated by Django 5.0.6 on 2025-03-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0023_remove_aitask_parent_task_remove_task_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='parent_task',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='parent_task',
            field=models.JSONField(default=list),
        ),
    ]
