# Generated by Django 5.0.6 on 2025-03-25 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0025_remove_aitask_parent_task_remove_task_parent_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='ai_task',
        ),
        migrations.CreateModel(
            name='AiSubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('ai_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_subtasks', to='goals.aitask')),
            ],
        ),
    ]
