# Generated by Django 5.0.6 on 2025-04-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0026_remove_subtask_ai_task_aisubtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
