# Generated by Django 5.0.6 on 2025-04-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0027_task_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitask',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
