# Generated by Django 5.0.6 on 2025-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0028_aitask_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisubtask',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
