# Generated by Django 5.0.6 on 2025-04-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0029_aisubtask_reminder_sent_subtask_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisubtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aisubtask',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
