# Generated by Django 5.0.6 on 2025-05-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0030_aisubtask_completed_at_aisubtask_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigoal',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
