# Generated by Django 5.0.6 on 2025-06-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0031_aigoal_tag_goal_tag_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisubtask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
