# Generated by Django 5.0.6 on 2025-06-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0032_alter_aisubtask_due_date_alter_subtask_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisubtask',
            name='ai_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='ai_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='ai_answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
