# Generated by Django 5.0.6 on 2025-07-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0034_routine_aisubtask_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='subtask_template_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='subtask_template_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
