# Generated by Django 5.0.6 on 2025-07-08 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0035_routine_subtask_template_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='goals.routine'),
        ),
        migrations.AddField(
            model_name='task',
            name='routine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='goals.routine'),
        ),
    ]
