# Generated by Django 5.0.6 on 2025-09-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0036_routine_reminder_time_subtask_routine_task_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='custom_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='custom_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months')], max_length=20, null=True),
        ),
    ]
