# Generated by Django 5.0.6 on 2025-09-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0037_routine_custom_interval_routine_custom_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisubtask',
            name='overdue_reason',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('unfinished', 'Unfinished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aitask',
            name='overdue_reason',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('unfinished', 'Unfinished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='overdue_reason',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('unfinished', 'Unfinished')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_reason',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('unfinished', 'Unfinished')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aisubtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('completed', 'Completed'), ('overdue', 'Overdue')], default='pending', max_length=20),
        ),
    ]
