# Generated by Django 5.0.6 on 2025-09-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0038_aisubtask_overdue_reason_aitask_overdue_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisubtask',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aitask',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subtask',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='overdue_notified',
            field=models.BooleanField(default=False),
        ),
    ]
