# Generated by Django 5.0.6 on 2025-09-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0040_dailytemplate_dailyactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('custom', 'Custom')], max_length=20),
        ),
    ]
