# Generated by Django 5.0.6 on 2025-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0042_aisubtask_created_at_subtask_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
