# Generated by Django 5.0.6 on 2025-10-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0043_dailyactivity_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
