# Generated by Django 5.0.6 on 2025-10-13 07:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0044_dailyactivity_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyactivity',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
