# Generated by Django 5.0.6 on 2025-10-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0046_dailyactivityhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='last_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
