# Generated by Django 5.0.6 on 2025-10-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0047_routine_last_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytemplate',
            name='is_daily_plan',
            field=models.BooleanField(default=False),
        ),
    ]
