# Generated by Django 5.0.6 on 2025-10-26 08:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0048_dailytemplate_is_daily_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailyTemplate',
            new_name='Template',
        ),
    ]
