# Generated by Django 5.0.6 on 2025-11-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0049_rename_dailytemplate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigoal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('pending', 'Pending')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='goal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('pending', 'Pending')], default='active', max_length=10),
        ),
    ]
