# Generated by Django 5.0.6 on 2025-11-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0050_aigoal_status_goal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigoal',
            name='emoji',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='emoji',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='emoji',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
