# Generated by Django 5.0.6 on 2025-01-22 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0001_initial'),
        ('goals', '0004_aigoal_aitask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aiinsight',
            name='goal',
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='ai_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='goals.aigoal'),
        ),
    ]
