# Generated by Django 5.0.6 on 2025-11-05 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_insights', '0002_remove_aiinsight_goal_aiinsight_ai_goal'),
        ('goals', '0049_rename_dailytemplate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinsight',
            name='ai_subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='goals.aisubtask'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='ai_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='goals.aitask'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='goals.subtask'),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='goals.task'),
        ),
    ]
